name: select_form_field
description: A Flutter select form field widget. It shows a list of options in a dropdown menu.
version: 2.0.2
homepage: https://github.com/m3uzz/select_form_field

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
